INSERT INTO tutorials(id,title,description,published) VALUES (1,'Way You Wanted Me, The (Sellaisena kuin sinä minut halusit)','Pasta - Rotini, Colour, Dry','true');
INSERT INTO tutorials(id,title,description,published) VALUES (2,'Swedish Auto','Sauce - Gravy, Au Jus, Mix','false');
INSERT INTO tutorials(id,title,description,published) VALUES (3,'Endurance','Sultanas','true');
INSERT INTO tutorials(id,title,description,published) VALUES (4,'Milk','Ocean Spray - Kiwi Strawberry','false');
INSERT INTO tutorials(id,title,description,published) VALUES (5,'Hot to Trot','Cookies - Assorted','false');
INSERT INTO tutorials(id,title,description,published) VALUES (6,'First Beautiful Thing, The (La prima cosa bella)','Ranchero - Primerba, Paste','false');
INSERT INTO tutorials(id,title,description,published) VALUES (7,'Scourge','Kellogs Cereal In A Cup','false');
INSERT INTO tutorials(id,title,description,published) VALUES (8,'Eye In The Sky (Gun chung)','Halibut - Fletches','true');
INSERT INTO tutorials(id,title,description,published) VALUES (9,'Quatre garçons pleins d''avenir','Salt - Rock, Course','false');
INSERT INTO tutorials(id,title,description,published) VALUES (10,'In the City (En la ciudad)','Bagel - Plain','false');
INSERT INTO tutorials(id,title,description,published) VALUES (11,'Bells of Capistrano','Energy Drink','false');
INSERT INTO tutorials(id,title,description,published) VALUES (12,'Transformers: Dark of the Moon','Pate - Cognac','true');
INSERT INTO tutorials(id,title,description,published) VALUES (13,'Blade Runner','Cake - Cake Sheet Macaroon','false');
INSERT INTO tutorials(id,title,description,published) VALUES (14,'Tuya''s Marriage (Tuya de hun shi)','Pepper Squash','false');
INSERT INTO tutorials(id,title,description,published) VALUES (15,'Crazy Sexy Cancer','Bonito Flakes - Toku Katsuo','true');
INSERT INTO tutorials(id,title,description,published) VALUES (16,'Tsatsiki, Morsan och Polisen','Arrowroot','true');
INSERT INTO tutorials(id,title,description,published) VALUES (17,'Poseidon Adventure, The','Lamb - Sausage Casings','true');
INSERT INTO tutorials(id,title,description,published) VALUES (18,'Marlowe','Sour Puss Raspberry','false');
INSERT INTO tutorials(id,title,description,published) VALUES (19,'Killer Shrews, The','Onion Powder','false');
INSERT INTO tutorials(id,title,description,published) VALUES (20,'Pocahontas','Artichoke - Bottom, Canned','true');
INSERT INTO tutorials(id,title,description,published) VALUES (21,'Escape to Athena','Cake - Box Window 10x10x2.5','false');
INSERT INTO tutorials(id,title,description,published) VALUES (22,'Legally Blonde 2: Red, White & Blonde','Fish - Soup Base, Bouillon','true');
INSERT INTO tutorials(id,title,description,published) VALUES (23,'Dark Blue World (Tmavomodrý svet)','Ham - Cooked','true');
INSERT INTO tutorials(id,title,description,published) VALUES (24,'Cruel Story of Youth (Seishun zankoku monogatari)','Bok Choy - Baby','true');
INSERT INTO tutorials(id,title,description,published) VALUES (25,'Spy Who Loved Me, The','Table Cloth 62x114 White','true');
INSERT INTO tutorials(id,title,description,published) VALUES (26,'Quatre garçons pleins d''avenir','Wine - Periguita Fonseca','true');
INSERT INTO tutorials(id,title,description,published) VALUES (27,'Alien from L.A.','Flower - Commercial Bronze','false');
INSERT INTO tutorials(id,title,description,published) VALUES (28,'Let the Right One In (Låt den rätte komma in)','Bag - Bread, White, Plain','false');
INSERT INTO tutorials(id,title,description,published) VALUES (29,'Caretakers, The','Squash - Butternut','false');
INSERT INTO tutorials(id,title,description,published) VALUES (30,'Kiss of the Vampire, The','Napkin - Beverge, White 2 - Ply','false');
INSERT INTO tutorials(id,title,description,published) VALUES (31,'Stay as You Are','Shortbread - Cookie Crumbs','false');
INSERT INTO tutorials(id,title,description,published) VALUES (32,'Getting Go, the Go Doc Project','Wine - Sake','false');
INSERT INTO tutorials(id,title,description,published) VALUES (33,'Great Waldo Pepper, The','Hersey Shakes','false');
INSERT INTO tutorials(id,title,description,published) VALUES (34,'Special When Lit','Bar - Sweet And Salty Chocolate','true');
INSERT INTO tutorials(id,title,description,published) VALUES (35,'Dead Space: Aftermath','Bread - Triangle White','false');
INSERT INTO tutorials(id,title,description,published) VALUES (36,'Lust for Gold','Hog / Sausage Casing - Pork','true');
INSERT INTO tutorials(id,title,description,published) VALUES (37,'Kon-Tiki','Yeast Dry - Fleischman','false');
INSERT INTO tutorials(id,title,description,published) VALUES (38,'Adventures of Pluto Nash, The','Lemon Pepper','false');
INSERT INTO tutorials(id,title,description,published) VALUES (39,'Loving Annabelle','Ice Cream - Life Savers','false');
INSERT INTO tutorials(id,title,description,published) VALUES (40,'Crimson Tide','Cheese - Goat','false');
INSERT INTO tutorials(id,title,description,published) VALUES (41,'Night Passage','Club Soda - Schweppes, 355 Ml','true');
INSERT INTO tutorials(id,title,description,published) VALUES (42,'Fight, Zatoichi, Fight (Zatôichi kesshô-tabi) (Zatôichi 8)','Jicama','false');
INSERT INTO tutorials(id,title,description,published) VALUES (43,'Dark Tower, The','Puree - Blackcurrant','false');
INSERT INTO tutorials(id,title,description,published) VALUES (44,'Rains of Ranchipur, The','Cheese - Pied De Vents','true');
INSERT INTO tutorials(id,title,description,published) VALUES (45,'Come Back to Me','Tomatoes - Plum, Canned','false');
INSERT INTO tutorials(id,title,description,published) VALUES (46,'Wild Orchid','Pork - Butt, Boneless','false');
INSERT INTO tutorials(id,title,description,published) VALUES (47,'Foxes','Napkin - Beverge, White 2 - Ply','true');
INSERT INTO tutorials(id,title,description,published) VALUES (48,'Bride of Chucky (Child''s Play 4)','Buffalo - Striploin','true');
INSERT INTO tutorials(id,title,description,published) VALUES (49,'Soul Man','Veal - Shank, Pieces','true');
INSERT INTO tutorials(id,title,description,published) VALUES (50,'The Well-Digger''s Daughter','Asparagus - White, Canned','true');